/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILixirStrategy,
  ILixirStrategyInterface,
} from "../ILixirStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ILixirVault",
        name: "_vault",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initializeVault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILixirStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): ILixirStrategyInterface {
    return new utils.Interface(_abi) as ILixirStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILixirStrategy {
    return new Contract(address, _abi, signerOrProvider) as ILixirStrategy;
  }
}
