/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IULMEvents, IULMEventsInterface } from "../IULMEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "userAmount0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "userAmount1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "pilotAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "Collect",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    name: "Deposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
      {
        indexed: false,
        internalType: "uint160",
        name: "sqrtPriceX96",
        type: "uint160",
      },
    ],
    name: "PoolCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "baseLiquidity",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "rangeLiquidity",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newBaseTickLower",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newBaseTickUpper",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newRangeTickLower",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newRangeTickUpper",
        type: "int24",
      },
    ],
    name: "PoolReajusted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "Withdrawn",
    type: "event",
  },
];

export class IULMEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IULMEventsInterface {
    return new utils.Interface(_abi) as IULMEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IULMEvents {
    return new Contract(address, _abi, signerOrProvider) as IULMEvents;
  }
}
