/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IUnipilotFactoryInterface extends utils.Interface {
  functions: {
    "createVault(address,address,uint24,uint160,string,string)": FunctionFragment;
    "getUnipilotDetails()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createVault",
    values: [string, string, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnipilotDetails",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnipilotDetails",
    data: BytesLike
  ): Result;

  events: {
    "GovernanceChanged(address,address)": EventFragment;
    "VaultCreated(address,address,uint24,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GovernanceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;
}

export type GovernanceChangedEvent = TypedEvent<
  [string, string],
  { _oldGovernance: string; _newGovernance: string }
>;

export type GovernanceChangedEventFilter =
  TypedEventFilter<GovernanceChangedEvent>;

export type VaultCreatedEvent = TypedEvent<
  [string, string, number, string],
  { _tokenA: string; _tokenB: string; _fee: number; _vault: string }
>;

export type VaultCreatedEventFilter = TypedEventFilter<VaultCreatedEvent>;

export interface IUnipilotFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUnipilotFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createVault(
      _tokenA: string,
      _tokenB: string,
      _fee: BigNumberish,
      _sqrtPriceX96: BigNumberish,
      _name: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getUnipilotDetails(
      overrides?: CallOverrides
    ): Promise<[string, string, string, number]>;
  };

  createVault(
    _tokenA: string,
    _tokenB: string,
    _fee: BigNumberish,
    _sqrtPriceX96: BigNumberish,
    _name: string,
    _symbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getUnipilotDetails(
    overrides?: CallOverrides
  ): Promise<[string, string, string, number]>;

  callStatic: {
    createVault(
      _tokenA: string,
      _tokenB: string,
      _fee: BigNumberish,
      _sqrtPriceX96: BigNumberish,
      _name: string,
      _symbol: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getUnipilotDetails(
      overrides?: CallOverrides
    ): Promise<[string, string, string, number]>;
  };

  filters: {
    "GovernanceChanged(address,address)"(
      _oldGovernance?: string | null,
      _newGovernance?: string | null
    ): GovernanceChangedEventFilter;
    GovernanceChanged(
      _oldGovernance?: string | null,
      _newGovernance?: string | null
    ): GovernanceChangedEventFilter;

    "VaultCreated(address,address,uint24,address)"(
      _tokenA?: string | null,
      _tokenB?: string | null,
      _fee?: null,
      _vault?: string | null
    ): VaultCreatedEventFilter;
    VaultCreated(
      _tokenA?: string | null,
      _tokenB?: string | null,
      _fee?: null,
      _vault?: string | null
    ): VaultCreatedEventFilter;
  };

  estimateGas: {
    createVault(
      _tokenA: string,
      _tokenB: string,
      _fee: BigNumberish,
      _sqrtPriceX96: BigNumberish,
      _name: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getUnipilotDetails(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createVault(
      _tokenA: string,
      _tokenB: string,
      _fee: BigNumberish,
      _sqrtPriceX96: BigNumberish,
      _name: string,
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getUnipilotDetails(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
