/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Burnable__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IUnipilotFarm",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUnipilotFarm__factory>;
    getContractFactory(
      name: "IUnipilotStake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUnipilotStake__factory>;
    getContractFactory(
      name: "ERC20T",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20T__factory>;
    getContractFactory(
      name: "Pilot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pilot__factory>;
    getContractFactory(
      name: "TestERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestERC20__factory>;
    getContractFactory(
      name: "UnipilotFarm",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UnipilotFarm__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Burnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Burnable>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IUnipilotFarm",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUnipilotFarm>;
    getContractAt(
      name: "IUnipilotStake",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUnipilotStake>;
    getContractAt(
      name: "ERC20T",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20T>;
    getContractAt(
      name: "Pilot",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pilot>;
    getContractAt(
      name: "TestERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestERC20>;
    getContractAt(
      name: "UnipilotFarm",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UnipilotFarm>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
