/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPriceFeeds, IPriceFeedsInterface } from "../IPriceFeeds";

const _abi = [
  {
    inputs: [],
    name: "getThePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPriceFeeds__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceFeedsInterface {
    return new utils.Interface(_abi) as IPriceFeedsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceFeeds {
    return new Contract(address, _abi, signerOrProvider) as IPriceFeeds;
  }
}
