/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRebaseEngine, IRebaseEngineInterface } from "../IRebaseEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "rebase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rebasePool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRebaseEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IRebaseEngineInterface {
    return new utils.Interface(_abi) as IRebaseEngineInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRebaseEngine {
    return new Contract(address, _abi, signerOrProvider) as IRebaseEngine;
  }
}
